name: Bug report
description: Reporte um problema no Diskill Message
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: O que aconteceu?
      description: Descreva o problema claramente.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Navegador
      placeholder: "Chrome / Edge / Firefox + versão"
    validations:
      required: true

  - type: input
    id: tm
    attributes:
      label: Tampermonkey (versão)
      placeholder: "ex.: 5.x"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Erros (se tiver)
      description: Cole aqui o trecho do log (sem expor token).
    validations:
      required: false
